package com.practice.scmsystem.utils;

public enum ITEMSTATUS {
	PROCURED, AT_SOURCE, IN_TRANSIT_TO_WAREHOUSE, IN_TRANSIT_TO_DESTINATION, AT_WAREHOUSE, AT_DESTINATION, DESTROYED, DAMAGED, MISSING;
}
