server:
   port: 8001

spring:
   application:
      name: department-service   
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8000/eureka
   instance:
      hostname: localhost